### ISSUE TITLE
compiling with pcl 1.6

### ISSUE THREAD

**Issue by martinGithub** [strawlab/python-pcl#16]
the binding has been test with PCL 1.5 and does not seem o compile with PCL 1.6.
I get he error

pcl.cpp:6378:21: error: ‘__pyx_t_8pcl_defs_MovingLeastSquares_t’ has no member named ‘reconstruct’
In file included from /usr/include/python2.7/numpy/ndarrayobject.h:26:0,
                 from /usr/include/python2.7/numpy/arrayobject.h:15,
                 from pcl.cpp:256:

this error seems similar to http://www.pcl-users.org/surface-reconstruction-error-td3829313.html and thus i guess it is due o a small change in the PCL API. Could hat be fixed ?
