### ISSUE TITLE
Can't build in Ubuntu 12.04

### ISSUE THREAD

**Issue by ckalas** [strawlab/python-pcl#65]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c pcl/_pcl.cpp -o build/temp.linux-x86_64-2.7/pcl/_pcl.o
    
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
    
    In file included from pcl/_pcl.cpp:245:0:
    
    pcl/shared_ptr_assign.h:1:29: fatal error: pcl/point_cloud.h: No such file or directory
    
    compilation terminated.
    
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-ILBAU6-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-HXf6ge-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-ILBAU6-build

In /usr/include/pcl-1.7 the files exists.

**Comment by ckalas** [comment]
It also complains the openni-dev is not installed - I have an need a ROS Hydro installation which has installed already libopenni-dev. Can this work instead of openni-dev with this package?

**Comment by Remi-C** [comment]
Hey,
I also use it on ubuntu 12.04 (64 and 32).
You need pcl 1.7 (default is 1.6)

Then I had the #59 issue, which is easily solved (had a space at the correct place)

maybe a `sudo ldconfig` before building?
